#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=96:00:00
#PBS -l vmem=30gb
#PBS -N cpac

# parse config.json for input parameters
preconfig=$(jq -r .preconfig config.json)
if [ "$preconfig" == "null" ] || [ "$preconfig" == "default" ]
    then
        preconfig=""
    else
        preconfig="--preconfig $preconfig"
fi

# get latest image if we don't already have one
if [ -f cpac-singularity-image.simg ]
  then
    echo "using existing C-PAC Singularity image"
  else
    echo "getting C-PAC Singularity image"
    time singularity pull cpac-singularity-image.simg shub://FCP-INDI/C-PAC || singularity pull cpac-singularity-image.simg docker://fcpindi/c-pac:latest
fi

# convert brainlife structure to BIDS
if [ ! -d bids ]
  then
    echo "restructuring data"
    bl2bids
fi


set -x
set -e

# run C-PAC
echo "running C-PAC"
mkdir -p output tmp
time singularity run -e -B $PWD/tmp:/tmp cpac-singularity-image.simg bids output participant $preconfig --save_working_dir
