#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=48:00:00
#PBS -l vmem=30gb
#PBS -N cpac

# parse config.json for input parameters
preconfig=$(jq -r .preconfig config.json)
if [ "$preconfig" == "" ] || [ "$preconfig" == "null" ] || [ "$preconfig" == "default" ]
    then
        preconfig=""
    else
        preconfig="--preconfig $preconfig"
fi

# get latest image if we don't already have one
if [ -f cpac-singularity-image.simg ]
  then
    echo "using existing C-PAC Singularity image"
  else
    echo "getting C-PAC Singularity image"
    time curl -LOJ https://4344-4733263-gh.circle-artifacts.com/0/cpac-singularity-image.simg
fi

# convert brainlife structure to BIDS
if [ ! -d bids ]
  then
    echo "restructuring data"
    bl2bids
fi

set -x
set -e

# run C-PAC
echo "running C-PAC"
mkdir -p output tmp

time singularity run -e -B $PWD/bids:/bids -B $PWD/output:/output -B $PWD/tmp:/tmp cpac-singularity-image.simg /bids /output participant $preconfig --save_working_dir
